// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_dUhQHFh6CxNlqjoZGI7mft5gmQoG7f8',
    appId: '1:266071218633:web:66cd84dffe28d85d5db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    authDomain: 'transgloble-2d53d.firebaseapp.com',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    measurementId: 'G-PKV59V7EJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3suEAfzSRXM1swoe9bdjEEQhcXSeTy9g',
    appId: '1:266071218633:android:dc6c9fafd16cca945db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1nRpCvQowpmKdTbfEPo0bMwSjSuvah1U',
    appId: '1:266071218633:ios:8a496b9f22cecb5f5db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1nRpCvQowpmKdTbfEPo0bMwSjSuvah1U',
    appId: '1:266071218633:ios:8a496b9f22cecb5f5db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_dUhQHFh6CxNlqjoZGI7mft5gmQoG7f8',
    appId: '1:266071218633:web:c4f3482c738b6a175db018',
    messagingSenderId: '266071218633',
    projectId: 'transgloble-2d53d',
    authDomain: 'transgloble-2d53d.firebaseapp.com',
    storageBucket: 'transgloble-2d53d.firebasestorage.app',
    measurementId: 'G-VE0KRKH7NJ',
  );

}