// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnml6vJJQz05so1pNmsyLpLCqdcFM6RAQ',
    appId: '1:531372125872:web:348b0f06ba434b74021575',
    messagingSenderId: '531372125872',
    projectId: 'transgolbe-a1eeb',
    authDomain: 'transgolbe-a1eeb.firebaseapp.com',
    databaseURL: 'https://transgolbe-a1eeb-default-rtdb.firebaseio.com/',
    storageBucket: 'transgolbe-a1eeb.firebasestorage.app',
    measurementId: 'G-RW1D2MLE7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPby0nbxfE12jWfeN1CNT9PifXE-a7C4',
    appId: '1:531372125872:android:af3635b777528f73021575',
    messagingSenderId: '531372125872',
    projectId: 'transgolbe-a1eeb',
    databaseURL: 'https://transgolbe-a1eeb-default-rtdb.firebaseio.com/',
    storageBucket: 'transgolbe-a1eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwPby0nbxfE12jWfeN1CNT9PifXE-a7C4',
    appId: '1:531372125872:ios:af3635b777528f73021575',
    messagingSenderId: '531372125872',
    projectId: 'transgolbe-a1eeb',
    databaseURL: 'https://transgolbe-a1eeb-default-rtdb.firebaseio.com/',
    storageBucket: 'transgolbe-a1eeb.firebasestorage.app',
    iosBundleId: 'com.example.transglobeAdmin',
  );

}